spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/





server:
  port: 8080

